import type { Config } from 'tailwindcss'

/**
 * NEXORA IoT design tokens — ported 1:1 from the Stitch design reference
 * (see nexora-iot/docs/design-tokens.md). Light theme only.
 */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: '#004ac6',
        'on-primary': '#ffffff',
        'primary-container': '#2563eb',
        'on-primary-container': '#eeefff',
        'on-primary-fixed': '#00174b',
        'on-primary-fixed-variant': '#003ea8',
        'primary-fixed': '#dbe1ff',
        'primary-fixed-dim': '#b4c5ff',
        'inverse-primary': '#b4c5ff',
        secondary: '#00687a',
        'on-secondary': '#ffffff',
        'secondary-container': '#57dffe',
        'on-secondary-container': '#006172',
        'on-secondary-fixed': '#001f26',
        'on-secondary-fixed-variant': '#004e5c',
        'secondary-fixed': '#acedff',
        'secondary-fixed-dim': '#4cd7f6',
        tertiary: '#3e3fcc',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#585be6',
        'on-tertiary-container': '#f1eeff',
        'on-tertiary-fixed': '#07006c',
        'on-tertiary-fixed-variant': '#2f2ebe',
        'tertiary-fixed': '#e1e0ff',
        'tertiary-fixed-dim': '#c0c1ff',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        background: '#faf8ff',
        'on-background': '#131b2e',
        surface: '#faf8ff',
        'on-surface': '#131b2e',
        'surface-variant': '#dae2fd',
        'on-surface-variant': '#434655',
        'surface-dim': '#d2d9f4',
        'surface-bright': '#faf8ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f2f3ff',
        'surface-container': '#eaedff',
        'surface-container-high': '#e2e7ff',
        'surface-container-highest': '#dae2fd',
        'surface-tint': '#0053db',
        'inverse-surface': '#283044',
        'inverse-on-surface': '#eef0ff',
        outline: '#737686',
        'outline-variant': '#c3c6d7',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        base: '4px',
        'stack-sm': '8px',
        'stack-md': '16px',
        'stack-lg': '32px',
        gutter: '16px',
        'container-padding': '24px',
        'header-height': '72px',
        'sidebar-width': '280px',
      },
      fontFamily: {
        'display-metrics': ['Manrope', 'sans-serif'],
        'headline-lg': ['Manrope', 'sans-serif'],
        'headline-lg-mobile': ['Manrope', 'sans-serif'],
        'headline-md': ['Manrope', 'sans-serif'],
        'title-sm': ['Manrope', 'sans-serif'],
        'body-lg': ['Manrope', 'sans-serif'],
        'body-md': ['Manrope', 'sans-serif'],
        'label-caps': ['Manrope', 'sans-serif'],
      },
      fontSize: {
        'display-metrics': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'title-sm': ['18px', { lineHeight: '24px', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '700' }],
      },
      boxShadow: {
        'card-hover': '0px 4px 20px rgba(37, 99, 235, 0.08)',
      },
    },
  },
  plugins: [],
} satisfies Config
